<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="TO_JSON" Id="{859d3522-49c4-4bdb-ba35-0ee9dd5ca77c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TO_JSON : STRING(255)
VAR_INPUT
	Input		: ANY;
END_VAR
VAR
	sTypeName	: STRING;
	sRes		: STRING(255);
	fbJson		: FB_JsonSaxWriter;
	fbJsonDataType	: FB_JsonReadWriteDataType;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[sTypeName := fbJsonDataType.GetDatatypeNameByAddress(TO_UDINT(Input.diSize), Input.pValue);
fbJsonDataType.AddJsonValueFromSymbol(fbJson, sTypeName, TO_UDINT(Input.diSize), Input.pValue);
fbJson.CopyDocument(sRes, SIZEOF(sRes));
TO_JSON := sRes;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>